# Generated by Django 5.0.4 on 2024-05-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_mission_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='static/profiles')),
            ],
        ),
        migrations.RemoveField(
            model_name='mission',
            name='profile_pic',
        ),
    ]
