# Generated by Django 5.0.4 on 2024-05-17 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
